# -*- coding: utf-8 -*-
"""ingest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18q8jTpiIjE_NKsyCmeEDt2TiWsl8zs8d
"""

import os, re, pickle
from dataclasses import dataclass
from typing import List, Dict
from pdfminer.high_level import extract_text
from openai import OpenAI
import numpy as np, faiss

EMBED_MODEL = "text-embedding-3-small"
INDEX_DIR   = "vectorstore"
os.makedirs(INDEX_DIR, exist_ok=True)
client = OpenAI()

@dataclass
class DocChunk:
    text: str
    meta: Dict

def _clean(s:str)->str:
    s = re.sub(r"\s+", " ", s)
    return s.strip()

def _chunk(text:str, file:str, size=1000, overlap=150):
    out, i = [], 0
    while i < len(text):
        piece = text[i:i+size]
        out.append(DocChunk(piece, {"file": file, "page": None, "text": piece}))
        i += size - overlap
    return out

def _embed(texts:List[str]) -> np.ndarray:
    emb = client.embeddings.create(model=EMBED_MODEL, input=texts)
    arr = np.array([e.embedding for e in emb.data], dtype="float32")
    faiss.normalize_L2(arr)
    return arr

def index_pdfs(uploaded_files: List) -> str:
    chunks = []
    for f in uploaded_files:
        txt = _clean(extract_text(f))
        chunks.extend(_chunk(txt, file=f.name))
    texts = [c.text for c in chunks]
    metas = [c.meta for c in chunks]
    vecs  = _embed(texts)
    dim = vecs.shape[1]
    index = faiss.IndexFlatIP(dim)
    index.add(vecs)
    idx_id = os.urandom(8).hex()
    faiss.write_index(index, f"{INDEX_DIR}/{idx_id}.faiss")
    with open(f"{INDEX_DIR}/{idx_id}.pkl","wb") as f:
        pickle.dump({"texts":texts, "metas":metas}, f)
    return idx_id

