# -*- coding: utf-8 -*-
"""rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XlilmNJsjNhtrebvKIdnNTUpb7uiypG_
"""

import pickle, faiss, numpy as np
from openai import OpenAI
client = OpenAI()
INDEX_DIR = "vectorstore"
EMBED_MODEL = "text-embedding-3-small"
CHAT_MODEL  = "gpt-4o-mini"

def _embed(q:str)->np.ndarray:
    v = client.embeddings.create(model=EMBED_MODEL, input=[q]).data[0].embedding
    v = np.array(v, dtype="float32").reshape(1, -1)
    faiss.normalize_L2(v)
    return v

def load_index(index_id:str):
    index = faiss.read_index(f"{INDEX_DIR}/{index_id}.faiss")
    with open(f"{INDEX_DIR}/{index_id}.pkl","rb") as f:
        store = pickle.load(f)
    return index, store["texts"], store["metas"]

def retrieve(index, texts, metas, query, k=5):
    qv = _embed(query)
    scores, idxs = index.search(qv, k)
    return [
        {"score": float(s), "text": texts[i], "meta": metas[i]}
        for i, s in zip(idxs[0], scores[0])
    ]

SYSTEM = "You're Genie AI. Be concise, never invent coverage, always cite [file:<name>]."

def answer_with_rag(query:str, retrieved:list)->str:
    ctx = "\n\n".join(f"[{r['meta'].get('file','doc')}] {r['text'][:600]}" for r in retrieved)
    messages = [
        {"role":"system","content":SYSTEM},
        {"role":"user","content":f"Context:\n{ctx}\n\nQuestion:{query}\nAnswer in bullets with citations."}
    ]
    r = client.chat.completions.create(model=CHAT_MODEL,temperature=0.2,messages=messages)
    return r.choices[0].message.content