# -*- coding: utf-8 -*-
"""router.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CCENee5uFojWs1lH-cqXH2vmPe61lpkL
"""

import re
from typing import Dict, Any
from pipelines.rag import load_index, retrieve, answer_with_rag

def _score_intent(text:str)->str:
    s=text.lower()
    if any(k in s for k in ["policy","covered","waiting","hospital"]): return "policy"
    if any(k in s for k in ["term","rider","premium","assured"]): return "term"
    if any(k in s for k in ["reject","non-network","missing document"]): return "rejection"
    if any(k in s for k in ["medicine","bill","pharmacy"]): return "medicine"
    if any(k in s for k in ["cost","estimate","price"]): return "cost"
    return "unknown"

def route_query(user_text:str, ss:Dict[str,Any])->Dict[str,Any]:
    intent=_score_intent(user_text)
    if intent=="policy":
        idx=ss.get("POLICY_IDX")
        if not idx: return {"text":"Upload policy PDFs and click Ingest first."}
        index,txts,metas=load_index(idx);hits=retrieve(index,txts,metas,user_text,k=5)
        return {"text":answer_with_rag(user_text,hits)}
    if intent=="term":
        idx=ss.get("TERM_IDX")
        if not idx: return {"text":"Upload term brochures and click Ingest first."}
        index,txts,metas=load_index(idx);hits=retrieve(index,txts,metas,user_text,k=5)
        return {"text":answer_with_rag(user_text,hits)}
    if intent=="rejection": return {"text":"Use Claim Rejection Predictor tab."}
    if intent=="medicine": return {"text":"Use Medicine Claim Generator tab."}
    if intent=="cost": return {"text":"Use Cost Estimator tab."}
    return {"text":"Sorry, couldn’t classify that question."}