# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IkpknWlogtk_3oIGpnhqD2ku8uAQiobl
"""

import streamlit as st
from router import route_query

st.title("🤖 Genie AI – Unified Chat")
q = st.text_input("Ask about your policy, claims or premiums:")
if "POLICY_IDX" not in st.session_state: st.session_state["POLICY_IDX"]=None
if "TERM_IDX" not in st.session_state: st.session_state["TERM_IDX"]=None

if st.button("Ask") and q:
    resp = route_query(q, st.session_state)
    st.markdown(resp["text"])